#!/bin/bash
address='192.168.1.1'
count=5
while :
do
	IFS=' ' read -a package <<< `ping -c $count $address | grep transmitted`
	avg=$((package[3]/package[0]*10))
	if [[ $avg -eq 10 ]]; then
		echo "Perfect!!!"
	elif [[ $avg -gt 5 ]]; then
		echo "Pretty Good!"
	elif [[ $avg -eq 0 ]]; then
		echo "Gotta check the connection."
	else
		echo "No Good."
	fi
	sleep 5s
done
